name: test retry action
on:
  push:
    branches:
      - master
jobs:
  # runs on branch pushes only
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: ainoya/retry@master
        name: ベータパッケージをスクラッチ組織にインストール
        with:
          timeout_minutes: 10
          retry_wait_seconds: 15
          max_attempts: 5
          command: |
            exit 1
